image: php:7.1-rc
before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

stages:
    - build
    - test
    - deploy

check_phpcs:
    script:
        - composer global require "squizlabs/php_codesniffer=*"
        - git clone https://github.com/djoos/Symfony2-coding-standard.git
        - ~/.composer/vendor/bin/phpcs --config-set installed_paths Symfony2-coding-standard
        - ~/.composer/vendor/bin/phpcs --standard=Symfony2 --extensions=php src/
    stage: build
