<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function getPublicAddressCustomer($customerId)
    {
        return $this->createQueryBuilder('a')
            ->where('a.customer=:customerId')
            ->andWhere('a.isPublic=:public')
            ->setParameter('customerId',$customerId)
            ->setParameter('public',true)
            ->getQuery()
            ->getResult();
    }
}
