<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function getPublicAddressCustomer($customerId)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.customer=:customerId')
            ->andWhere('a.isPublic=:public')
            ->orWhere('a.creator=:customerId')
            ->setParameter('customerId',$customerId)
            ->setParameter('public',true)
            ->getQuery()
            ->getResult();
    }

    public function getPublicAddressOrCreator($customerId=null,$creatorId){
        return $this->createQueryBuilder('a')
            ->andWhere('a.customer=:customerId')
            ->andWhere('a.isPublic=:public')
            ->orWhere("a.creator=:creatorId AND a.isPublic=:noPublic AND a.customer=:customerId")
//            ->andWhere('a.isPublic=:noPublic')
//            ->andWhere('a.customer=:customerId')
            ->setParameter('customerId',$customerId)
            ->setParameter('public',true)
            ->setParameter('creatorId',$creatorId)
            ->setParameter('noPublic',false)
            ->getQuery()
            ->getResult();
    }
    
}
