<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AssignmentRequest;

/**
 * AssignmentRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentRequestRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchCurrentAssignmentInfo($shipmentId,$driverId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $currentAssignResult = $qb->select('a')
            ->from('AppBundle:AssignmentRequest','a')
            ->where('a.shipment=:shipmentId')
            ->andWhere('a.driver=:driverId')
            ->andWhere('a.status=:assignmentStatus')
            ->setParameter('shipmentId',$shipmentId)
            ->setParameter('driverId',$driverId)
            ->setParameter('assignmentStatus',AssignmentRequest::STATUS_WAITING)
            ->getQuery()
            ->getSingleResult();

        return $currentAssignResult;
    }
}
