<?php

namespace AppBundle\Repository;

/**
 * BusinessTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
