<?php

namespace AppBundle\Repository;

/**
 * CustomerScoreHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerScoreHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
