<?php

namespace AppBundle\Repository;

/**
 * CustomerDeviceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerDeviceHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
