<?php

namespace AppBundle\Repository;

/**
 * CustomerDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
