<?php

namespace AppBundle\Repository;

/**
 * DriverScoreHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverScoreHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
