<?php

namespace AppBundle\Repository;

/**
 * ScoreHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
