<?php

namespace AppBundle\Repository;

/**
 * ShipmentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
