<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShipmentInvoiceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ShipmentInvoiceRepository extends EntityRepository
{
}
