<?php

namespace AppBundle\Repository;

/**
 * ShipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnknownShipmentRepository extends \Doctrine\ORM\EntityRepository
{
}
