<?php

namespace Roapp\RestaurantBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
}
