<?php

namespace Roapp\RestaurantBundle\Repository;

/**
 * RestaurantShipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantShipmentRepository extends \Doctrine\ORM\EntityRepository
{
}
